/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import database.DBconnect;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Sheha Dulanjaya
 */
public class patientDischarge extends javax.swing.JFrame {
Connection con = null;
ResultSet rs=null;
PreparedStatement pst=null;
Statement st = null;

        String bid=null;
        String admitdate=null;
        String bprice=null;
        String sid=null;
        String sprice=null;
        String pname =null;
        String nic=null;
        String sname=null;
        int sadd=0;
    /**
     * Creates new form patientDischarge
     */
    public patientDischarge() {
        initComponents();
        con = DBconnect.connect();
        
        Toolkit tk=Toolkit.getDefaultToolkit();
            int xsize=(int) tk.getScreenSize().getWidth();
            int ysize=(int) tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        srch1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_1 = new javax.swing.JTable();
        rno1 = new javax.swing.JTextField();
        day1 = new javax.swing.JTextField();
        echrg1 = new javax.swing.JTextField();
        tot1 = new javax.swing.JTextField();
        pamt1 = new javax.swing.JTextField();
        bal1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtar1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtar2 = new javax.swing.JTextArea();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        srch3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_3 = new javax.swing.JTable();
        rno3 = new javax.swing.JTextField();
        day3 = new javax.swing.JTextField();
        echrg3 = new javax.swing.JTextField();
        tot3 = new javax.swing.JTextField();
        pamt3 = new javax.swing.JTextField();
        bal3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_4 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PID", "Name", "Bed no", "Admit date", "room price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_1);
        if (tbl_1.getColumnModel().getColumnCount() > 0) {
            tbl_1.getColumnModel().getColumn(0).setResizable(false);
            tbl_1.getColumnModel().getColumn(1).setResizable(false);
            tbl_1.getColumnModel().getColumn(2).setResizable(false);
            tbl_1.getColumnModel().getColumn(2).setHeaderValue("Bed no");
            tbl_1.getColumnModel().getColumn(3).setResizable(false);
            tbl_1.getColumnModel().getColumn(3).setHeaderValue("Admit date");
            tbl_1.getColumnModel().getColumn(4).setHeaderValue("room price");
        }

        rno1.setEditable(false);

        day1.setEditable(false);

        echrg1.setEditable(false);

        tot1.setEditable(false);

        pamt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pamt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pamt1KeyTyped(evt);
            }
        });

        bal1.setEditable(false);

        jLabel1.setText("Room/Bed No");

        jLabel2.setText("Days to pay");

        jLabel3.setText("External charges");

        jLabel4.setText("Total");

        jLabel5.setText("Paid Amount");

        jLabel6.setText("Balance");

        tbl_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service ID", "Service", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_2);
        if (tbl_2.getColumnModel().getColumnCount() > 0) {
            tbl_2.getColumnModel().getColumn(0).setResizable(false);
            tbl_2.getColumnModel().getColumn(1).setResizable(false);
            tbl_2.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(srch1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pamt1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bal1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rno1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tot1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(echrg1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(echrg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pamt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtar1.setColumns(20);
        txtar1.setRows(5);
        jScrollPane3.setViewportView(txtar1);

        jButton6.setText("Refersh Bill");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Print Bill");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Checkout");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(34, 34, 34)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PatientID", jPanel2);

        txtar2.setColumns(20);
        txtar2.setRows(5);
        jScrollPane6.setViewportView(txtar2);

        jButton13.setText("Refersh Bill");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Print Bill");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Checkout");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbl_3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PID", "Name", "Bed no", "Admit date", "room price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_3MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbl_3);
        if (tbl_3.getColumnModel().getColumnCount() > 0) {
            tbl_3.getColumnModel().getColumn(0).setResizable(false);
            tbl_3.getColumnModel().getColumn(1).setResizable(false);
            tbl_3.getColumnModel().getColumn(2).setResizable(false);
            tbl_3.getColumnModel().getColumn(2).setHeaderValue("Bed no");
            tbl_3.getColumnModel().getColumn(3).setResizable(false);
            tbl_3.getColumnModel().getColumn(3).setHeaderValue("Admit date");
            tbl_3.getColumnModel().getColumn(4).setHeaderValue("room price");
        }

        rno3.setEditable(false);

        day3.setEditable(false);

        echrg3.setEditable(false);

        tot3.setEditable(false);

        pamt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pamt3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pamt3KeyTyped(evt);
            }
        });

        bal3.setEditable(false);

        jLabel13.setText("Room/Bed No");

        jLabel14.setText("Days to pay");

        jLabel15.setText("External charges");

        jLabel16.setText("Total");

        jLabel17.setText("Paid Amount");

        jLabel18.setText("Balance");

        tbl_4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service ID", "Service", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tbl_4);
        if (tbl_4.getColumnModel().getColumnCount() > 0) {
            tbl_4.getColumnModel().getColumn(0).setResizable(false);
            tbl_4.getColumnModel().getColumn(1).setResizable(false);
            tbl_4.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(srch3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pamt3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bal3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(day3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rno3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tot3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(echrg3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(echrg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pamt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(34, 34, 34)
                        .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NIC", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton3.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        tbl_1.removeAll();
        
        
        srch(1);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    srch(srch3.getText());    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbl_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_1MouseClicked
int row=tbl_1.getSelectedRow();
        
        String Table_click=(tbl_1.getModel().getValueAt(row,2).toString());
        
        rno1.setText(Table_click); 
         calc(admitdate,bprice,sadd); // TODO add your handling code here:
    }//GEN-LAST:event_tbl_1MouseClicked

    private void pamt3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pamt3KeyReleased
String pbal =pamt3.getText();
int pb=Integer.parseInt(pbal);
String totbal =tot3.getText();
int pb1=Integer.parseInt(totbal);

String balance=Integer.toString(pb-pb1);
bal3.setText(balance);

// TODO add your handling code here:
    }//GEN-LAST:event_pamt3KeyReleased

    private void pamt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pamt1KeyReleased
String pbal =pamt1.getText();
int pb=Integer.parseInt(pbal);
String totbal =tot1.getText();
int pb1=Integer.parseInt(totbal);

String balance=Integer.toString(pb-pb1);
bal1.setText(balance);        // TODO add your handling code here:
    }//GEN-LAST:event_pamt1KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 String dayrec=day1.getText();
 String total =tot1.getText();
 String paid=pamt1.getText();
 String bal=bal1.getText();
 if(!"".equals(total)){
        String mText= "                                 SAITAM HOSPITAL                               \n"
        + "--------------------------------------------------------------------------\n"
        + "Guest Name : " +pname+ "\n\n"
        + "Room no    : "+bid+"\n\n"
        + "Room Price : "+bprice+"\n\n"
        + "Charge For Days : "+dayrec+"\n\n"
        +"Total Price      : Rs "+total+".00\n\n"
                +"Paid Amount      : Rs "+paid+".00\n\n"
                +"Balance      : Rs "+bal+".00\n\n"
        + "--------------------------------------------------------------------------\n\n"
        +"                                 THANK YOU                                \n"
        +"Saitam \n"
        +"Airport road\n"
        +"Katunayake.\n"
        +"Fax : 032222213"
        +"Tel : 032222214";
         
        txtar1.setText(mText);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    }
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

String dayrec=day3.getText();
 String total =tot3.getText();
 String paid=pamt3.getText();
 String bal=bal3.getText();
 if(!"".equals(total)){
        String mText= "                                 SAITAM HOSPITAL                               \n"
        + "--------------------------------------------------------------------------\n"
        + "Guest Name : " +pname+ "\n\n"
        + "Room no    : "+bid+"\n\n"
        + "Room Price : "+bprice+"\n\n"
        + "Charge For Days : "+dayrec+"\n\n"
        +"Total Price      : Rs "+total+".00\n\n"
                +"Paid Amount      : Rs "+paid+".00\n\n"
                +"Balance      : Rs "+bal+".00\n\n"
        + "--------------------------------------------------------------------------\n\n"
        +"                                 THANK YOU                                \n"
        +"Saitam \n"
        +"Airport road\n"
        +"Katunayake.\n"
        +"Fax : 032222213"
        +"Tel : 032222214";
         
        txtar2.setText(mText);
 }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if(!"".equals(txtar1.getText())){
    try {
        boolean complete=txtar1.print();
        if(complete){
            JOptionPane.showMessageDialog(null, "done printing","information",JOptionPane.INFORMATION_MESSAGE);
             txtar1.setText(null);
        }
        else{
            JOptionPane.showMessageDialog(null,"printing canceled","printer",JOptionPane.ERROR_MESSAGE);
        }
    } catch (PrinterException ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
    }
else{
    JOptionPane.showMessageDialog(null, "Please press refresh bill button!");
}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tbl_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_3MouseClicked
int row=tbl_3.getSelectedRow();
        
        String Table_click=(tbl_3.getModel().getValueAt(row,2).toString());
        
        rno3.setText(Table_click); 
         calc2(this.admitdate,bprice,sadd); 

        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_3MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
if(!"".equals(txtar2.getText())){
    try {
        boolean complete=txtar2.print();
        if(complete){
            JOptionPane.showMessageDialog(null, "done printing","information",JOptionPane.INFORMATION_MESSAGE);
            txtar2.setText(null);
        }
        else{
            JOptionPane.showMessageDialog(null,"printing canceled","printer",JOptionPane.ERROR_MESSAGE);
        }
    } catch (PrinterException ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
    }
else{
    JOptionPane.showMessageDialog(null, "Please press refresh bill button!");
}  


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
tbl_3.setValueAt("",0,0);
tbl_3.setValueAt("",0,1);
tbl_3.setValueAt("",0,2);
tbl_3.setValueAt("",0,3);
tbl_3.setValueAt("",0,4);

tbl_4.setValueAt("",0,0);
tbl_4.setValueAt("",0,1);
tbl_4.setValueAt("",0,2);

tbl_3.clearSelection();

rno3.setText("");
day3.setText("");
echrg3.setText("");
pamt3.setText("");
tot3.setText("");
bal3.setText("");
srch3.setText("");

txtar2.setText("");






// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
tbl_1.setValueAt("",0,0);
tbl_1.setValueAt("",0,1);
tbl_1.setValueAt("",0,2);
tbl_1.setValueAt("",0,3);
tbl_1.setValueAt("",0,4);

tbl_2.setValueAt("",0,0);
tbl_2.setValueAt("",0,1);
tbl_4.setValueAt("",0,2);

tbl_1.clearSelection();

rno1.setText("");
day1.setText("");
echrg1.setText("");
pamt1.setText("");
tot1.setText("");
bal1.setText("");
srch1.setText("");

txtar1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pamt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pamt1KeyTyped
char c=evt.getKeyChar();
if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pamt1KeyTyped

    private void pamt3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pamt3KeyTyped
char c=evt.getKeyChar();
if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }              // TODO add your handling code here:
    }//GEN-LAST:event_pamt3KeyTyped


    public void calc(String dte,String roomCrg,int SrvceCrg){
        
        
        
        String s2=dte;
        try{
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime now = LocalDateTime.now();
        String s1=(dtf.format(now));
            
       SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");

        Date date1;
         Date date2;
        
            date1 = f.parse(s1);
            date2 = f.parse(s2);
            System.out.println(f.format(date1));
            Calendar day = Calendar.getInstance();
    Calendar day2 = Calendar.getInstance(); 
    day.setTime(date1);
    day2.setTime(date2);
        String v3="";
    int daysBetween = day.get(Calendar.DAY_OF_YEAR) - day2.get(Calendar.DAY_OF_YEAR);
     v3=Integer.toString(daysBetween);
    if(0==daysBetween){
        day1.setText("0");
       
    }
    else{
    day1.setText(v3);  
    int result2 = Integer.parseInt(roomCrg);
     int result = Integer.parseInt(v3);
    
    
    int tot=(result*result2)+SrvceCrg;
    String total=Integer.toString(tot);
    String Servicechrg=Integer.toString(SrvceCrg);
    echrg1.setText(Servicechrg);
    tot1.setText(total);
    
    }
        
        }    
       
        catch (ParseException ex) {
        Logger.getLogger(patientDischarge.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}
    public void calc2(String dte,String roomCrg,int SrvceCrg){
        
        
        
        String s2=dte;
        try{
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime now = LocalDateTime.now();
        String s1=(dtf.format(now));
            
       SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");

        Date date1;
         Date date2;
        
            date1 = f.parse(s1);
            date2 = f.parse(s2);
            System.out.println(f.format(date1));
            Calendar day = Calendar.getInstance();
    Calendar day2 = Calendar.getInstance(); 
    day.setTime(date1);
    day2.setTime(date2);
        String v3="";
    int daysBetween = day.get(Calendar.DAY_OF_YEAR) - day2.get(Calendar.DAY_OF_YEAR);
     v3=Integer.toString(daysBetween);
    if(0==daysBetween){
        day3.setText("0");
       
    }
    else{
    day3.setText(v3);  
    int result2 = Integer.parseInt(roomCrg);
     int result = Integer.parseInt(v3);
    
    
    int tot=(result*result2)+SrvceCrg;
    String total=Integer.toString(tot);
    String Servicechrg=Integer.toString(SrvceCrg);
    echrg3.setText(Servicechrg);
    tot3.setText(total);
    
    }
        
        }    
       
        catch (ParseException ex) {
        Logger.getLogger(patientDischarge.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}
    
    public void srch(int type){
        
    String pid=srch1.getText();//meka get karagannawa textbox eken
        
        
        try{
             String sql0="SELECT * from reg_patient where PID=?";
            pst=con.prepareStatement(sql0);
            pst.setString(1, pid);
            rs=pst.executeQuery();
            if(rs.next()){
                
                pname=rs.getString("fname");
                tbl_1.setValueAt(pid, 0, 0);
                tbl_1.setValueAt(pname, 0, 1);
            }
            String sql="SELECT * from admitward where PID=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, pid);
            rs=pst.executeQuery();
            if(rs.next()){
                bid=rs.getString("bedno");
                admitdate=rs.getString("admitdate");
                tbl_1.setValueAt(bid, 0, 2);
                tbl_1.setValueAt(admitdate, 0, 3);
            }
            
            String sql1="SELECT * from ward_info where bedno=?";
            pst=con.prepareStatement(sql1);
            pst.setString(1, bid);
            rs=pst.executeQuery();
            if(rs.next()){
                bprice=rs.getString("price");
                tbl_1.setValueAt(bprice, 0, 4);                
            }
            
            String sql2="SELECT * from patient_service where patientID=?";
            pst=con.prepareStatement(sql2);
            pst.setString(1, pid);
            rs=pst.executeQuery();
            if(rs.next()){
                sid=rs.getString("serviceID");
                sname=rs.getString("serviceName");
                tbl_2.setValueAt(sid, 0, 0);
                tbl_2.setValueAt(sname, 0, 1);
            }
            
            String sql3="SELECT * from serviceinfo where serviceNo=?";
            pst=con.prepareStatement(sql3);
            pst.setString(1, sid);
            rs=pst.executeQuery();
            while(rs.next()){
                sprice=rs.getString("serviceCharge");
                sadd=+Integer.parseInt(sprice);
                tbl_2.setValueAt(sprice, 0, 2);
            }
            
            System.out.println(bid);
            System.out.println(admitdate);
            System.out.println(bprice);
            System.out.println(sid);
            System.out.println(sprice);
            System.out.println(pname);
            
            
        }
        catch(Exception e)
        {
            System.out.println("Error in getting data from db");
            System.out.println(e.getMessage());
        }
   
}
     public void srch(String nid){
         
         // String nid=srch3.getText();//meka get karagannawa textbox eken
        String pid=null;
        
        try{
             String sql0="SELECT * from reg_patient where NIC=?";
            pst=con.prepareStatement(sql0);
            pst.setString(1, nid);
            rs=pst.executeQuery();
            if(rs.next()){
                
                pname=rs.getString("fname");
                pid=rs.getString("PID");
                tbl_3.setValueAt(pid, 0, 0);
                tbl_3.setValueAt(pname, 0, 1);
            }
            String sql="SELECT * from admitward where PID=?";
            pst=con.prepareStatement(sql);
            pst.setString(1, pid);
            rs=pst.executeQuery();
            if(rs.next()){
                bid=rs.getString("bedno");
                admitdate=rs.getString("admitdate");
                tbl_3.setValueAt(bid, 0, 2);
                tbl_3.setValueAt(admitdate, 0, 3);
            }
            
            String sql1="SELECT * from ward_info where bedno=?";
            pst=con.prepareStatement(sql1);
            pst.setString(1, bid);
            rs=pst.executeQuery();
            if(rs.next()){
                bprice=rs.getString("price");
                tbl_3.setValueAt(bprice, 0, 4);                
            }
            
            String sql2="SELECT * from patient_service where patientID=?";
            pst=con.prepareStatement(sql2);
            pst.setString(1, pid);
            rs=pst.executeQuery();
            if(rs.next()){
                sid=rs.getString("serviceID");
                sname=rs.getString("serviceName");
                tbl_4.setValueAt(sid, 0, 0);
                tbl_4.setValueAt(sname, 0, 1);
            }
            
            String sql3="SELECT * from serviceinfo where serviceNo=?";
            pst=con.prepareStatement(sql3);
            pst.setString(1, sid);
            rs=pst.executeQuery();
            while(rs.next()){
                sprice=rs.getString("serviceCharge");
                sadd=+Integer.parseInt(sprice);
                tbl_4.setValueAt(sprice, 0, 2);
            }
            
            System.out.println(bid);
            System.out.println(admitdate);
            System.out.println(bprice);
            System.out.println(sid);
            System.out.println(sprice);
            System.out.println(pname);
            
            
        }
        catch(Exception e)
        {
            System.out.println("Error in getting data from db");
            System.out.println(e.getMessage());
        }
   
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientDischarge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientDischarge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientDischarge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientDischarge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientDischarge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bal1;
    private javax.swing.JTextField bal3;
    private javax.swing.JTextField day1;
    private javax.swing.JTextField day3;
    private javax.swing.JTextField echrg1;
    private javax.swing.JTextField echrg3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pamt1;
    private javax.swing.JTextField pamt3;
    private javax.swing.JTextField rno1;
    private javax.swing.JTextField rno3;
    private javax.swing.JTextField srch1;
    private javax.swing.JTextField srch3;
    private javax.swing.JTable tbl_1;
    private javax.swing.JTable tbl_2;
    private javax.swing.JTable tbl_3;
    private javax.swing.JTable tbl_4;
    private javax.swing.JTextField tot1;
    private javax.swing.JTextField tot3;
    private javax.swing.JTextArea txtar1;
    private javax.swing.JTextArea txtar2;
    // End of variables declaration//GEN-END:variables
}
